### ISSUE TITLE
EncFSy_console crashes 

### ISSUE THREAD

**Issue by shujaat-github** [miyabe/encfsy#4]
**Environment:**

- Windows 11
- Visual Studio 2019
- 64-bit, Release build of **cryptopp-CRYPTOPP_8_6_0, EncFSy_lib, and EncFSy_console**
- [Dokany v1.5.1.1000 ](https://github.com/dokan-dev/dokany/releases/tag/v1.5.1.1000)

**Exception thrown:**
The following exception is thrown when I open **Microsoft Visio** file from Mounted Drive.
![image](https://user-images.githubusercontent.com/99479518/187191023-36271bc5-0bef-40fa-9bf4-c4a028d72042.png)

**Comment by mimidesunya** [comment]
I have never seen such a problem.
And unfortunately I do not have Visio.
Do you have any problems with anything other than Visio?
Meow

**Comment by shujaat-github** [comment]
@mimidesunya Thanks for reply. 
Up till now I have found only Visio which makes this issue to appear but I will soon test other File Formats & Softwares and will report any issues I come across.

By the way, I get the above issue each and every time when I open a Visio file from the Mounted Drive.

**Comment by shujaat-github** [comment]
Apart from **Visio File** that always fail with exception to load from **EncFS Virtual Drive**, I have found that **MP3, MP4, MKV, and 3GP** files can't be played with Windows built-in players like **Media Player, Movies & TV, and Windows Media Player** although these are supported files and can be played normally.  Errors that the Players show are attached below:

![image](https://user-images.githubusercontent.com/99479518/188855748-931d6902-1141-4e5a-a27d-84c2093a4da7.png)

**Media Player:**
![image](https://user-images.githubusercontent.com/99479518/188856515-4395b74d-3838-4d66-bccb-2ff7c4010829.png)

**Movies & TV**
![image](https://user-images.githubusercontent.com/99479518/188856596-b246d592-7bd3-433f-9bb8-23eb5f36043b.png)

**Windows Media Player**  
![image](https://user-images.githubusercontent.com/99479518/188856875-05ba526b-5636-4d17-b994-8f2e27e73ea9.png)

**Comment by mimidesunya** [comment]
Thanks for the report, we have reproduced the symptoms on Movies & TV. I am working on it
Meow!

**Comment by shujaat-github** [comment]
[Benchmark of Dokany v1.5.1.1000 vs v2.0.3.1000](https://github.com/dokan-dev/dokany#benchmark-v1511000-vs-v2031000) shows that Dokany **v2.0.3.1000** is way faster than **v1.5.1.1000**. 
It would be great if you upgrade Dokany to the latest version to reduce the **time and energy** spent by **EncFSy** users while using it.

**Comment by mimidesunya** [comment]
Now, I released EncFSy built with Dokany 2.0.5.1000.
And fixed the bug about Movies & TV.
Thank you for your reports.
Meow

**Comment by shujaat-github** [comment]
@mimidesunya Going to thoroughly test it and report any problems if I find.

**Comment by shujaat-github** [comment]
For now, I tested and found problems in Microsoft **Word** 2019,  Microsoft **Excel** 2019,  Microsoft **PowerPoint** 2019, and Microsoft **Visio** 2019.

**Reproduce:**
Open Virtual Drive, Right Click and Create New Microsoft Word Document. Open the newly created document from the Virtual Drive and write some content in it. Now as soon as you try to **Save the Document** the Word Application **hangs and crashes without saving the data** although EncFSy Virtual Drive doesn't crash.

I found the same issue in **Excel & PowerPoint** 

However, when I try to open a Visio file, **Path not found** error is shown by the Visio Application and the **EncFSy Virtual Drive crashes** and disappears from the File Explorer.

**Comment by mimidesunya** [comment]
Now I released new version that supports NTFS alternative streams.
I believe it resolved MS Word, Excel problems.
Meow meow!

**Comment by shujaat-github** [comment]
Tested MS Word, Excel, PowerPoint, PDF Files, Text Files, Video Files(3GP, MKV, MP4), and Audio Files(MP3). All of them worked flawlessly except those mentioned below.

Audio File **AIFF** format & MS **Visio**. Sample Aiff and Visio files are attached here.
[Sample Aiff & Visio File.zip](https://github.com/mimidesunya/encfsy/files/9596302/Sample.Aiff.Visio.File.zip)

While **Microsoft Media Player can play .aiff** format audios from non-encrypted drives but it can't play from **encfsy virtual drive**.
![image](https://user-images.githubusercontent.com/99479518/190953541-ac1db206-7e26-4f67-aa68-6e72ee597535.png)

Just like before, MS **Visio** simply **crashes** the EncFSy Virtual Drive while opening Visio File. As Virtual Drive crashes so MS Visio shows **File Not Found** message.
![image](https://user-images.githubusercontent.com/99479518/190953816-20ce6fa1-dc68-491e-a9fb-45c095c700cc.png)

I will do rigorous testing once I pass through **Visio** and .**aiff** Audio File issues.

**Comment by shujaat-github** [comment]
I will do rigorous testing once I pass through **Visio** and .**aiff** Audio File issues.

**Comment by shujaat-github** [comment]
### Update for EncFSy v0.13

Issues with audio file in **.aiff format & MS Visio** still not resolved. 

Tested _with_ and _without_ **--alt-stream**  using following command line arguments:
`encfs.exe C:\EncFSy_Test_Dir M --alt-stream`

**Comment by mimidesunya** [comment]
The AIFF problem could not be reproduced.
Are you using the desktop version of following Visio?
https://www.microsoft.com/microsoft-365/visio/microsoft-visio-plans-and-pricing-compare-visio-options?activetab=tabs%3aprimaryr1

**Comment by shujaat-github** [comment]
Yes I am using the Desktop Version of the Visio 2019. 

I can't play **.aiff audio files** from the **EncFSy Virtual Drive** using **Microsoft Media Player**. 

![image](https://user-images.githubusercontent.com/99479518/190994044-ea5dfe37-e17e-4370-a620-dedaf2df9cca.png)

While Visio throughs this error in code:
![image](https://user-images.githubusercontent.com/99479518/190994265-c6161bbe-5c20-4883-be50-3e8ae9a367b2.png)

**Comment by mimidesunya** [comment]
I found the cause about Visio and fixed it.
Please test version 0.14.
Meow

**Comment by shujaat-github** [comment]
**Simply Outstanding!**

**Visio** now works **flawlessly**! 

**Aiff audio file** has still loading problem in **Microsoft Media Player**.

Now going to test Version 0.14 more rigorously. Report will take around a day or two.

**Comment by shujaat-github** [comment]
@mimidesunya Before completing a full report I found something very important so I thought I should share with you and that is while testing for **.cpp** and **.h** file formats I created a sample **C++ Console Application** in EncFSy Virtual Drive using **Visual Studio 2022 Community Edition** and I found that VS throws an error message and also it's **intellisence** doesn't work.

**Reproduce:**
Open **Visual Studio 2022 Community Edition**, click on **Create a new project**, choose **C++ Console App**, click **Next**, Set **Location** in **EncFS Virtual Drive**, click on **Create**, now as soon as the VS loads the project, it shows the following message given in the screenshot. This message is not shown whenever I create project in non-EncFS Drive. I just click on OK to discard message but the **Intellisence** doesn't work.

![image](https://user-images.githubusercontent.com/99479518/191452088-7441c596-18fc-42b5-87bf-df53cb0f3c7d.png)

Also I **can't build the project** although I can build it if I create it in non-EncFSy Drive.

![image](https://user-images.githubusercontent.com/99479518/191455583-4ed59d19-4ef7-48d5-b9c8-132a84c2463f.png)

**Comment by shujaat-github** [comment]
I found another problem similar to the previous problem.

While testing for **[rust-lang](https://www.rust-lang.org/)** file types I found that I can't even create a rust project in EncFSy Virtual Drive.
I have **[Rust V1.63.0](https://www.rust-lang.org/)**, using **[Visual Studio Code V1.71.2](https://code.visualstudio.com/)** on **Windows 11**, & **[rust-analyzer](https://github.com/rust-lang/rust-analyzer)** extension for VS Code if that can help in EncFSy Debugging.

![image](https://user-images.githubusercontent.com/99479518/191481592-da903f3c-38dd-4e7e-845b-bba31d71af93.png)

**Comment by shujaat-github** [comment]
Apart from the **previous two issues**, I have attached a testing report below which covers some more issues.

Amazingly, **EncFSy has improved a lot** and the table below shows lots of **green rows**!

The red cells are the ones that need to be fixed in EncFSy to make it a **highly stable** C++ encrypted file system software & library.

![image](https://user-images.githubusercontent.com/99479518/191893352-8c5e204b-6464-4ca2-abf5-8f28ab657832.png)

**Comment by mimidesunya** [comment]
Thank you for your thoughtful report.
Perhaps the AIFF problem is caused by no buffering mode.
Simply, I disabled no buffering mode.
Because of encrypted files cannot align on the sector size.
Meow!

**Comment by shujaat-github** [comment]
Tested **EncFSy 0.15** and to my surprise, all the file formats mentioned in the previous report started working **flawlessly**!

**[This ](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253371765)**& **[this ](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253514066)** issue still exists.


![image](https://user-images.githubusercontent.com/99479518/191940669-a74b6c37-795a-4440-a1e7-251b6c57bcd8.png)

**Comment by mimidesunya** [comment]
I have resolved https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253514066 issue.
Meow.

**Comment by shujaat-github** [comment]
@mimidesunya I have found that [#4 (comment)](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253514066) issue is partially solved. 
In the below screenshot I have pointed the errors  caused by EncFSy. Due to these errors the **cargo run** command fails to run Rust project.

![image](https://user-images.githubusercontent.com/99479518/192197336-47638342-2cbf-4117-b004-f2eef55e283e.png)

**Comment by shujaat-github** [comment]
**[Updated]**
What I noticed is that if I create a **rust** project in some **Other Drive** and **compile** it in that same drive and then if I copy the project to **EncFSy Drive** and compile it then no build error occurs apart from the **warning** saying **"could not canonicalize path"**. 

This means EncFSy face some issues **when compiling rust project** using **cargo run** command. Issues may include failing to create some critical file or folder in the project etc.

**Comment by shujaat-github** [comment]
I think it's **.pdb** file that creates problems. In both **Visual Studio C++** and **Rust** case the compiler tries to create **.pdb** file in the build directory during compilation. In both cases EncFSy fails to create it.

**sample_project->target-debug** directory in the normal drive:
![image](https://user-images.githubusercontent.com/99479518/192257043-23decd3f-bae7-4a6b-870c-6f582c4c93f4.png)

**sample_project->target-debug** directory in the EncFSy drive:
![image](https://user-images.githubusercontent.com/99479518/192257350-dd81f560-e5f5-4a21-9692-1d8bc46a0433.png)

**Comment by mimidesunya** [comment]
I have confirmed that GetFinalPathNameByHandle does not work.
Maybe it is the Dokany problem.
I continue to look into this.
Meow...

**Comment by shujaat-github** [comment]
@mimidesunya I have posted **[canonicalizing path issue](https://github.com/dokan-dev/dokany/issues/1113)** on Dokany.

**Comment by shujaat-github** [comment]
Apart from [Rust issue ](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253514066)I can't reproduce [Visual Studio issue](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253371765) in [Dokany Mirror](https://github.com/dokan-dev/dokany/tree/master/samples/dokan_mirror). 

**Mirror** just works without throwing any warning or error when creating and building C++ Application in Visual Studio.

**Comment by shujaat-github** [comment]
@mimidesunya I have **[found](https://github.com/dokan-dev/dokany/issues/1113#issuecomment-1260377647)** that if I run **[Dokany Mirror](https://github.com/dokan-dev/dokany/tree/master/samples/dokan_mirror)** with command line option `/o` to enable `Mount Manager` then I can flawlessly create, compile, and run Rust project in the Dokan Virtual Drive. 

Now I wonder what security side effects this option will have if EncFSy enables Mount Manager.

**Comment by mimidesunya** [comment]
I resolved Rust issue.
Fixed a critical bug that could have corrupted files.
--dokan-mount-manager option is now supported in the GUI.
Thanks a lot. You are good tester.
Meow meow!

**Comment by shujaat-github** [comment]
Just tested **Rust** project in **EncFSy v0.17** Virtual Drive!
EncFSy can now create, compile and run Rust projects **flawlessly**!

![image](https://user-images.githubusercontent.com/99479518/192779132-c37f0380-eb88-4bf2-bc69-956d6b3430b7.png)

**Comment by shujaat-github** [comment]
**Half Good News!** Visual Studio can now compile and run C++ application! **But** VS shows the same below error message as before while creating project and hence intellisense doesn't work.

![image](https://user-images.githubusercontent.com/99479518/192781858-7be955b0-19d7-4065-99a0-6fd03a54c810.png)

**Comment by mimidesunya** [comment]
I found a bug when reading empty files.
I fixed it!
Meow.

**Comment by shujaat-github** [comment]
Tested **EncFSy 0.18**, I found that although the error message has gone but **intellisense** still doesn't work in the project which is created inside EncFSy Virtual Drive.

The following message is shown by VS in the status bar although this message is not shown when I create the same project in some other normal drive:
![image](https://user-images.githubusercontent.com/99479518/192935946-22dc28d8-0ff8-4c62-a5a4-ddb7079b9cbd.png)

**Comment by shujaat-github** [comment]
@mimidesunya I have found that both **[Dokany Mirror](https://github.com/dokan-dev/dokany/tree/master/samples/dokan_mirror)** and **[CppCryptFS ](https://github.com/bailey27/cppcryptfs)** do not show the issue which I have reported in the previous comment. This means EncFSy might have missed a minor thing while upgrading to the latest Dokany v2? I might be seriously wrong!

I will test EncFSy more rigorously and share a full report with you once the Visual Studio issue is resolved. I am already proud that EncFSy is quite stable among all other similar projects!

**Comment by shujaat-github** [comment]
I have found something that might help you in debugging.

I have found that Visual Studio creates a **PROJECT_NAME.ipch** file in the location shown in the snapshot when I create project in **normal drive**:

![image](https://user-images.githubusercontent.com/99479518/192948214-bbce49fc-ae66-4170-a567-7741bf93569c.png)


**But** Visual Studio doesn't create it when I create project in **EncFSy Virtual Drive**:

![image](https://user-images.githubusercontent.com/99479518/192947605-f1bf30cd-2475-407a-bdf3-9238f6edc2a9.png)

**Comment by shujaat-github** [comment]
Additionally I noticed a difference in the size of the **Browse.VC.db** and **Browse.VC.opendb** files in both the **normal drive** and the **EncFSy drive** in freshly created projects.

**Normal Drive:**

![image](https://user-images.githubusercontent.com/99479518/192950689-83b7755e-5ac0-4801-88e2-7952516743cd.png)


**EncFSy Drive:**

![image](https://user-images.githubusercontent.com/99479518/192950395-de02bad4-17aa-4dda-836e-2e86b9af4783.png)

**Comment by mimidesunya** [comment]
May be it caused by case-sensitivity of file names.
There are some solutions, but it requires forethought and time.
Meow.

**Comment by shujaat-github** [comment]
Trying to fix this problem from my side but since I am not that much expert I can't find the solution yet. But I'm still excited to test EncFSy as hard as possible once EncFSy fixes this issue.

**Comment by mimidesunya** [comment]
Now, case-insensitive mode is available!
Plase use --case-insensitive option.
Meow!

**Comment by shujaat-github** [comment]
Very amazing work! 
Visual Studio C++ projects can now be created, compiled and run :100:  **flawlessly!**

Wonderful & Ultra Awesome!  :partying_face:

**Comment by shujaat-github** [comment]
The report is being prepared and will be shared in the coming days.

**Comment by mimidesunya** [comment]
You are very welcome.
Meow meow.

**Comment by shujaat-github** [comment]
Report is attached here. Everything is green :heart_eyes:
![image](https://user-images.githubusercontent.com/99479518/195003094-c8cb0d84-0e17-4bb3-b348-ab3c023789e5.png)

**Comment by mimidesunya** [comment]
Thank you very much!
Can we close this issue?
Meow

**Comment by mimidesunya** [comment]
I'm sorry to leave but I'm going to close it.
Meow!

**Comment by shujaat-github** [comment]
Since all the issues listed in this thread have been resolved :100: so it was the right decision to close it :thumbsup:

**Comment by shujaat-github** [comment]
I'll keep testing :heart_on_fire:EncFSy:heart_on_fire: so if I find some new issues I'll create a new issue for them.
